CREATE TABLE calls (
	sr_no VARCHAR NOT NULL,
	sr_type VARCHAR NOT NULL,
	department TEXT,
	sr_method TEXT,
	sr_status TEXT,
	zip_code VARCHAR(5),
	district INT,
	city TEXT,
	county TEXT,
	sr_year INT,
	open_time INTERVAL,
	open_time_d INTERVAL,
	total_seconds INTERVAL,
	sr_created TIMESTAMP,
	sr_created_dt TIMESTAMP,
	sr_close TIMESTAMP,
	sr_close_dt TIMESTAMP,
	sr_change TIMESTAMP,
	sr_update TIMESTAMP,
	map_pg VARCHAR,
	map_tile VARCHAR,
	state_x VARCHAR,
	state_y VARCHAR,
	lat VARCHAR,
	long VARCHAR,
	lat_long POINT,
	sr_location TEXT,
	st_number VARCHAR,
	st_name TEXT
	);
	
